smartprep/admins/urls.py
from django.urls import path

from admins import views

urlpatterns = [
    path('dashboard/', views.admin_dashboard),
    path('category_form/', views.categories_form),
    path('get_category/', views.get_category),

    path('show_course/', views.show_course),
    path('show_contact/', views.show_contact),
    path('form/', views.form),
    path('delete_category/<int:categories_id>', views.delete_category)

]

smartprep/materials/urls.py
from django.urls import path

from materials import views
urlpatterns = [

   # path('home', views.content2),
    path('home/', views.home),
    path('courses/', views.course),
    path('get_course_category/<int:categories_id>', views.get_course_category),
    path('cart/',views.cart),
    path('checkout/',views.checkout),
    path('update_item/',views.updateItem),

    path('process_order/', views.processOrder),
    path('details/<int:i_id>/', views.details),

    path('orderhistory/',views.orderhistory),
    path('delete_history/<int:file_orderid>',views.delete_history),

    path('mylearning/',views.mylearning),
    # path('content/', views.content2)

]

smartprep/smartprep/urls.py
from django.urls import path, include

urlpatterns = [
    path('materials/', include('materials.urls')),
    path('admins/', include('admins.urls')),
    path('', include('accounts.urls')),
    path('lecturer/', include('lecturer.urls'))

]

smartprep/materials/models.py
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db import models
from django.contrib.auth.models import User
from accounts.forms import CreateUserForm

# Create your models here.
# categories table
class Categories(models.Model):
    category_Name=models.CharField(validators=[MinLengthValidator(9), MaxLengthValidator(1000)],
                                  null=True, max_length=1000)

    category_Description=models.TextField(validators=[MinLengthValidator(9), MaxLengthValidator(3000)],
                                  null=True, max_length=3000)
    category_Image=models.FileField(upload_to='static/uploaded_Files')
    def __str__(self):
        return self.category_Name


# courses table
class Courses(models.Model):
    course_Name=models.CharField(max_length=1000)
    category=models.ForeignKey(Categories, on_delete=models.CASCADE)
    course_Description = models.TextField(validators=[MinLengthValidator(9), MaxLengthValidator(3000)],

                                            null=True, max_length=3000)
    course_Image = models.FileField(upload_to='static/uploaded_Files')
    price=models.FloatField(default=20)
    digital=models.BooleanField(default=False,null=True,blank=False)
    def __str__(self):
        return self.course_Name



class Order (models.Model):
    customer=models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered=models.DateTimeField(auto_now_add=True)
    complete=models.BooleanField(default=False)
    transaction_id=models.CharField(max_length=100, null=True)
    delerivered_status=models.BooleanField(default=False)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total



class OrderItem(models.Model):
    product=models.ForeignKey(Courses, on_delete=models.SET_NULL,blank=True,null=True)
    order=models.ForeignKey(Order,on_delete=models.SET_NULL, blank=True, null=True)
    quantity=models.IntegerField(default=0, null=True, blank=True)
    data_added=models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer=models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True)
    order=models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address=models.CharField(max_length=200, null=True)
    city=models.CharField(max_length=200,null=True)
    state=models.CharField(max_length=200,null=True)
    zipcode=models.CharField(max_length=200, null=True)
    date_added =models.DateTimeField(auto_now_add=True)


# lecturers table
class Lectures(models.Model):
    lecture_Name=models.CharField(max_length=3000)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    lecture_content= models.TextField(validators=[MinLengthValidator(9), MaxLengthValidator(3000)],
                                            null=True, max_length=3000)
    def __str__(self):
        return self.lecture_Name


# class Categories_Courses(models.Model):
#     category = models.ForeignKey(Categories, on_delete=models.CASCADE)
#     category_Image=models.ForeignKey(Categories, on_delete=models.CASCADE)
#     category_Details = models.ForeignKey(Categories, on_delete=models.CASCADE)
#
#     course = models.ForeignKey(Courses, on_delete=models.CASCADE)
#     def __str__(self):
#         return self.category

smartprep/materials/forms.py
from django import forms
from  django.forms import ModelForm
from .models import Categories, Courses, Lectures



class CategoriesForm(ModelForm):
    class Meta:
        model=Categories
        fields='__all__'

class CoursesForm(ModelForm):
    class Meta:
        model=Courses
        fields="__all__"


class LecturesForm(ModelForm):
    class Meta:
        model=Lectures
        fields = "__all__"

smartprep/materials/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect

# Create your views here.
from accounts.auth import learner_only
from materials.filters import CourseFilter, CatFilter
from materials.models import Categories, Courses, Order
from .models import *
from django.http import JsonResponse
import json
import datetime
import os
from django.db import connection

@learner_only
def home(request):
    category=Categories.objects.all().order_by('-id')
    context={
        'category_material':category,
        'activate_home':'active'

    }

    return render(request, 'materials/content.html', context )

# for courses in course page
@learner_only
def course(request):
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0,'shipping': False}
        cartItems = order['get_cart_items']

    courses=Courses.objects.all().order_by('course_Name')
    courses_filter = CourseFilter(request.GET, queryset=courses)
    courses_final = courses_filter.qs

    context={
        'course_material':courses_final,
        'user_course_filter':courses_filter,
        'activate_courses':'active',
        'cartItems': cartItems,
        'items': items,
        'order': order,
        # cartItems=order['get_cart_items']
    }

    return render(request, 'materials/courses.html', context )

#retrieving course according to category
@learner_only
def get_course_category(request,categories_id):
    category=Categories.objects.get(id=categories_id)
    context={
        'category':category
    }
    return render(request,'materials/get_course_category.html',context)

# recently added courses
def details(request,i_id):
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0,'shipping': False}
        cartItems = order['get_cart_items']
    files=Courses.objects.get(id=i_id)
    context={
        'i':files,
        'activate_courses': 'active',
        'cartItems': cartItems,
        'items': items,
        'order': order,
    }
    return render(request, 'materials/details.html', context)




def cart(request):
    if request.user.is_authenticated:
        customer=request.user
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items=[]
        order={'get_cart_total':0,'get_cart_items':0,'shipping': False}
        cartItems = order['get_cart_items']

    context={'items':items,
             'order':order,
             'cartItems':cartItems}
    return render(request,'materials/cart.html',context)

def checkout(request):
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0, 'shipping': False}
        cartItems = order['get_cart_items']
    context={'items':items ,
             'order':order,
             'cartItems':cartItems}
    return render(request,'materials/checkout.html',context)



def updateItem(request):
    data=json.loads(request.body)
    iId=data['iId']
    action = data['action']

    print('Action:',action)
    print('iId:',iId)

    customer = request.user
    i=Courses.objects.get(id=iId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created=OrderItem.objects.get_or_create(order=order, product=i)

    if action =='add':
        orderItem.quantity=(orderItem.quantity +1)
    elif action =='remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <=0:
        orderItem.delete()



    return JsonResponse('item was added',safe=False)

def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        total = float(data['form']['total'])
        order.transaction_id = transaction_id

        if total == float(order.get_cart_total):
            order.complete = True
        order.save()

        if order.shipping == True:
            ShippingAddress.objects.create(
                customer=customer,
                order=order,
                address=data['shipping']['address'],
                city=data['shipping']['city'],
                state=data['shipping']['state'],
                zipcode=data['shipping']['zipcode'],
            )


    else:
        print('user not logged in')
    return JsonResponse('Payment complete',safe=False)




def orderhistory(request):
    userid = request.user.id
    cursor=connection.cursor()
    cursor.execute("""SELECT dzz.id, dop.quantity,dxx.address,dxx.city,dmf.course_Name,dmf.price,dmf.course_Image,
case dzz.complete
        when 1 then 'completed'
        when 0 then 'incompleted'
    end as amount,
case dzz.delerivered_status
    when 1 then 'delivered'
    when 0 then 'Pending'
 end as status    
FROM materials_order dzz
left join materials_orderitem dop on  dop.order_id=dzz.id
left join materials_shippingaddress dxx on dxx.order_id=dzz.id
left join materials_courses dmf on dop.product_id=dmf.id
left join auth_user ddd on ddd.id=dzz.customer_id
where dzz.customer_id = %s""",(userid,))
    details=cursor.fetchall()
    result=[]
    for detail in details:
        keys=('orderid','quantity','address','city','course_Name','price','course_Image','complete')
        result.append(dict(zip(keys,detail)))

    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total': 0, 'get_cart_items': 0}
        cartItems = order['get_cart_items']
    context={
        "detail":result,
        'items': items,
        'order': order,
        'cartItems': cartItems,
    }
    return render(request, 'materials/orderhistory.html', context)

def delete_history(request,file_orderid):
    history=Order.objects.get(id=file_orderid)
    history.delete()
    return redirect('/materials/orderhistory/')

def mylearning(request):
    return render(request,'materials/mylearning.html')

smartprep/materials/templates/materials/cart.html

{% extends 'layout.html' %}
{% load static %}
{% load bootstrap%}

{% block title %}
<title>Cart</title>
{% endblock title %}

{% block main_content %}
<section class="">

    <div class="container" >
         <div class="row">
			 <div class="shoppingcart mt-5">
				 <h1 class="mt-5">Shopping Cart</h1>


			 </div>

			 <h5>{{order.get_cart_items}} Courses in Cart</h5>


			  <div class="col-lg-9 ">

			<div class="box-element ">
<!--				<div class="cart-row1">-->

<!--					<div style="flex:4"><strong>  Course</strong></div>-->
<!--					<div style="flex:1"><strong>Quantity</strong></div>-->
<!--					<div style="flex:1"><strong>Total</strong></div>-->
<!--				</div>-->
				{% for item in items %}

				<div class="cart-row">
					<div style="flex:1"><img class="row-image" src="/{{item.product.course_Image}}"></div>
					<div style="flex:4; font-weight:500;"><p><strong>{{item.product.course_Name}}</strong></p>
						<div class="head">
							<span class="fa fa-star checked"></span>
					<span class="fa fa-star checked"></span>
					<span class="fa fa-star checked"></span>
					<span class="fa fa-star checked"></span>
					<span class="fa fa-star"></span>  &nbsp;4.9 &nbsp; 76,209 ratings

						</div>

					</div>

					<div style="flex:1" class="remove">
<!--						<p class="quantity">{{item.quantity}}</p>-->
						<div data-i="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" style="flex:1"><p>Remove</p>


					   </div>
						<p>Save for later</p>

<!--						<div class="quantity">-->
<!--							<img data-i="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">-->

<!--							<img data-i="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">-->
<!--						</div>-->
					</div>
					<div style="flex:1; color:#30649C; font-size:18px;"><p>${{item.get_total}}  <i class="fa fa-tag" aria-hidden="true"></i></p></div>
				</div>
             {% endfor %}
			</div>
		</div>

		<div class="col-lg-3 ">
			<div class="box-element">
<!--				<div class="cart-row">-->
<!--					<a href="/materials/courses/" class="btn btn-outline-dark" href="">&#x2190; Course</a>-->

<!--				<br>-->
<!--				<br>-->

<!--				</div>-->




						<h5>Total:
							</h5>
					<h1 style="color:#30649C;font-size:50px;"><strong> ${{order.get_cart_total}}</strong></h1>

						<a  style="margin:5px; background:#30649C; color:white; width:100%; font-size:20px;" class="btn" href="/materials/checkout/">Checkout</a>




			</div>

		</div>

	</div>
    </div>
</section>

{% endblock main_content %}

smartprep/materials/templates/materials/content.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap%}

{% block title %}
<title>Course</title>
{% endblock title %}

{% block main_content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600&display=swap');

*{
	list-style: none;
	font-family: 'Montserrat', sans-serif;
	margin: 0;
	padding: 0;
	box-sizing: border-box;
}


.view_item img{
	width: 100px;
	height:100px
}

.wrapper{
	width: 1000px;
	margin: 20px auto;
}

.links{
	margin-bottom: 25px;
	color: #b3b9b9;
	background: #fff;
	padding: 15px ;
	border-radius: 3px;
	height:150px;
	display: flex;
	align-items:flex-end;

}

.links ul{
	display: flex;
<!--	justify-content: center;-->
    float:left
}

.links ul li{
	margin: 0 15px;
	font-weight: 600;
	text-transform: uppercase;
	letter-spacing: 3px;
	font-size: 20px;
	cursor: pointer;
}

.links ul li:hover,
.links ul li.active{
	color: black;
}

.view_main{
	background: #fff;
	border-radius: 3px;
	padding: 15px;
}

.list-view .view_item {
	background: #fff;
	border: 1px solid #e2efe1;
	margin: 10px;
	padding: 10px 20px;
	display: flex;
	align-items: center;
}

.list-view .view_item:last-child{
	margin-bottom: 0;
}

.list-view .view_item .vi_left{
	margin-right: 25px;
}

.view_item .title{
	font-weight: 600;
}

.view_item .content{
	margin: 5px 0;
	font-size: 14px;
	line-height: 22px;
	font-weight: 400;
}

.view_item .btn{
	background: #30649C;
	padding: 5px 10px
	border-radius: 3px;
	color: #fff;
	text-align: center;

	font-weight: 700;
	cursor: pointer;

	font-size:11px
}

.view_item .btn:hover{
	background: #000;
}

.grid-view{
	width: 100%;

}

.grid-view .view_item {
    height:410px;
	display: inline-block;
    border: 1px solid #e2efe1;
    width: 300px;
    padding: 10px;
    text-align: center;
    margin: 10px;

}

.grid-view .view_item .vi_left{
	margin-bottom: 10px;
}

.grid-view .view_item .btn{
	margin: 0 auto;
}



.content-content{height:140px;
overflow:hidden;
padding:0 25px}

.content{overflow:hidden;
display:-webkit-box;
-webkit-box-orient:vertical;
-webkit-line-clamp:5
}




.grid-view .view_item .vi_left img {width:240px;
height:170px;
}


.bottom-CE{
display:flex;
 justify-content:space-between;
}



.types{padding-top:0.1px}
.searchh{padding:15px}
ol, ul {
    padding-left: 0rem;
}

.serch{padding:0 15px}
::placeholder {
  color: black}

  .box{

	width: 100%;
	height: 50px;
	background-color: white;
	border-radius: 30px;
	display: flex;
	align-items: center;
	padding: 20px;
	border: 1px solid rgb(218, 220, 224);

}

.box > input{
	flex: 1;
	height: 40px;
	border: none;
	outline: none;
	font-size: 16px;
	padding-left: 10px;


}
</style>

<!-- ----------our Course-------- -->

<div class="types mt-5 " style="background-color:white">
<!--    <h1 class="heading1">-->
<!--        <span>O</span>-->
<!--        <span>U</span>-->
<!--        <span>R</span>-->
<!--        <span class="space"></span>-->
<!--        <span>C</span>-->
<!--        <span>O</span>-->
<!--        <span>U</span>-->
<!--        <span>R</span>-->
<!--        <span>S</span>-->
<!--        <span>E</span>-->
<!--        <span>S</span>-->
<!--    </h1>-->
    <div class="wrapper">
        <div class="serch">
        <div class="boxx" style="margin: auto;">
            <i class="fa fa-search" aria-hidden="true"></i>
        <input autocomplete="off" placeholder="Search Courses" aria-label="Search" class="sc-irKDMX fyRspk"  align="center" id="myButton" value="">
        </div>
        </div>

        <div class="links pt-5">
            <ul>
                <li data-view="grid-view" class="li-grid">
                    <i class="fas fa-th-large"></i>
                    Categories
                </li>
                 <li data-view="list-view" class="li-list active">
                    <i class="fas fa-th-list"></i>
                    Courses
                </li>
            </ul>
        </div>
        <div class="view_main">

            <div class="view_wrap grid-view" style="display: none;">

                {% for i in category_material %}
                <div class="view_item">
                    <div class="vi_left">
                        <img src="/{{i.category_Image}}" alt="Relevant Image">
                    </div>
                    <div class="vi_right" style="height:200px">
                        <p class="title">{{i.category_Name}}</p>
                        <div class="content-content">
                        <p class="content"   style="  text-align: justify; color:black">{{i.category_Description}}</p>
                        </div>

                        <div class="bottom-CE">
                            <span class="btn" ><a href="/materials/get_course_category/{{i.id}}" style="text-decoration:none; color:white"> Explore > </a></span>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

             <div class="view_wrap list-view" style="display: block;">

                {% for i in category_material %}
                 {%for j in i.courses_set.all %}
                <div class="view_item">
                    <div class="vi_left">
                        <img src="/{{j.course_Image}}" alt="Relevant Image">
                    </div>
                    <div class="vi_right">
                        <p class="title">{{j.course_Name}}</p>
                        <p class="content" style="overflow:hidden;
                        display:-webkit-box;
                        -webkit-box-orient:vertical;
                        -webkit-line-clamp:2">
                            {{j.course_Description}}</p>
                        <div class="btn"> Explore ></div>
                    </div>
                </div>
                 {% endfor %}
                  {% endfor %}

            </div>
        </div>
    </div>
</div>
    <script>
        var li_links = document.querySelectorAll(".links ul li");
        var view_wraps = document.querySelectorAll(".view_wrap");
        var list_view = document.querySelector(".list-view");
        var grid_view = document.querySelector(".grid-view");

        li_links.forEach(function(link){
            link.addEventListener("click", function(){
                li_links.forEach(function(link){
                    link.classList.remove("active");
                })

                link.classList.add("active");

                var li_view = link.getAttribute("data-view");

                view_wraps.forEach(function(view){
                    view.style.display = "none";
                })

                if(li_view == "list-view"){
                    list_view.style.display = "block";
                }
                else{
                    grid_view.style.display = "block";
                }
            })
        })

    </script>

<script type="text/javascript">
    document.getElementById("myButton").onclick = function () {
        location.href = "/materials/courses/";
    };
</script>
    {% endblock main_content %}

smartprep/materials/templates/materials/courseeeeeee.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap%}

{% block title %}
<title>Course</title>
{% endblock title %}

{% block main_content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600&display=swap');

*{
	list-style: none;
	font-family: 'Montserrat', sans-serif;
	margin: 0;
	padding: 0;
	box-sizing: border-box;
}



.view_item img{
	width: 100px;
	height:100px
}

.wrapper{
	width: 1000px;
	margin: 20px auto;
}

.links{
	margin-bottom: 25px;
	color: #b3b9b9;
	background: #fff;
	padding: 15px;
	border-radius: 3px;
}

.links ul{
	display: flex;
	justify-content: center;
}

.links ul li{
	margin: 0 15px;
	font-weight: 600;
	text-transform: uppercase;
	letter-spacing: 3px;
	font-size: 20px;
	cursor: pointer;
}

.links ul li:hover,
.links ul li.active{
	color: #30649C;
}

.view_main{
	background: #fff;
	border-radius: 3px;
	padding: 15px;
}

.list-view .view_item {
	background: #fff;
	border: 1px solid #e2efe1;
	margin: 10px;
	padding: 10px 20px;
	display: flex;
	align-items: center;
}

.list-view .view_item:last-child{
	margin-bottom: 0;
}

.list-view .view_item .vi_left{
	margin-right: 25px;
}

.view_item .title{
	font-weight: 600;
}

.view_item .content{
	margin: 5px 0;
	font-size: 14px;
	line-height: 22px;
	font-weight: 400;
}

.view_item .btn{
	background: #30649C;
	padding: 5px 10px
	border-radius: 3px;
	color: #fff;
	text-align: center;

	font-weight: 700;
	cursor: pointer;

	font-size:11px
}

.view_item .btn:hover{
	background: #000;
}

.grid-view{
	width: 100%;

}

.grid-view .view_item {
    height:410px;
	display: inline-block;
    border: 1px solid #e2efe1;
    width: 300px;
    padding: 10px;
    text-align: center;
    margin: 10px;

}

.grid-view .view_item .vi_left{
	margin-bottom: 10px;
}

.grid-view .view_item .btn{
	margin: 0 auto;
}



.content-content{height:140px;
overflow:hidden;
padding:0 25px}

.content{overflow:hidden;
display:-webkit-box;
-webkit-box-orient:vertical;
-webkit-line-clamp:5
}




.grid-view .view_item .vi_left img {width:240px;
height:170px;
}


.bottom-CE{
display:flex;
 justify-content:space-between;
}

</style>

<!-- ----------our Course-------- -->

<div class="types mt-5 p-5">
    <h1 class="heading1">
        <span>O</span>
        <span>U</span>
        <span>R</span>
        <span class="space"></span>
        <span>C</span>
        <span>O</span>
        <span>U</span>
        <span>R</span>
        <span>S</span>
        <span>E</span>
        <span>S</span>
    </h1>
    <div class="wrapper">
        <div class="links">
            <ul>
                <li data-view="grid-view" class="li-grid">
                    <i class="fas fa-th-large"></i>
                    Categories
                </li>
                 <li data-view="list-view" class="li-list active">
                    <i class="fas fa-th-list"></i>
                    Courses
                </li>
            </ul>
        </div>
        <div class="view_main">

            <div class="view_wrap grid-view" style="display: none;">

                {% for i in category_material %}
                <div class="view_item">
                    <div class="vi_left">
                        <img src="/{{i.category_Image}}" alt="Relevant Image">
                    </div>
                    <div class="vi_right" style="height:200px">
                        <p class="title">{{i.category_Name}}</p>
                        <div class="content-content">
                        <p class="content"   style="  text-align: justify; color:black">{{i.category_Description}}</p>
                        </div>

                        <div class="bottom-CE">
                            <span class="btn"> Explore > </span>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>

             <div class="view_wrap list-view" style="display: block;">

                {% for i in category_material %}
                 {%for j in i.courses_set.all %}
                <div class="view_item">
                    <div class="vi_left">
                        <img src="/{{j.course_Image}}" alt="Relevant Image">
                    </div>
                    <div class="vi_right">
                        <p class="title">{{j.course_Name}}</p>
                        <p class="content" style="overflow:hidden;
                        display:-webkit-box;
                        -webkit-box-orient:vertical;
                        -webkit-line-clamp:2">
                            {{j.course_Description}}</p>
                        <div class="btn">Explore ></div>
                    </div>
                </div>
                 {% endfor %}
                  {% endfor %}

            </div>
        </div>
    </div>
</div>
    <script>
        var li_links = document.querySelectorAll(".links ul li");
        var view_wraps = document.querySelectorAll(".view_wrap");
        var list_view = document.querySelector(".list-view");
        var grid_view = document.querySelector(".grid-view");

        li_links.forEach(function(link){
            link.addEventListener("click", function(){
                li_links.forEach(function(link){
                    link.classList.remove("active");
                })

                link.classList.add("active");

                var li_view = link.getAttribute("data-view");

                view_wraps.forEach(function(view){
                    view.style.display = "none";
                })

                if(li_view == "list-view"){
                    list_view.style.display = "block";
                }
                else{
                    grid_view.style.display = "block";
                }
            })
        })

    </script>
    {% endblock main_content %}

smartprep/materials/templates/materials/get_course_category.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap%}

{% block title %}
<title>Course</title>
{% endblock title %}

{% block main_content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600&display=swap');


.description{width:55%;
text-align:justify}
</style>

<!-- ----------our Course-------- -->

<div class="types mt-5  pt-5" style="background-color:white" >
    <div class="wrapper pt-5">
        <div class="links">
<!--            -->
<!--             <h1 class="heading1">-->
<!--        <span>{{category.category_Name}}</span>-->

<!--        </h1>-->
            <div class="left-side">
                <div class="topic">
                <h1 class="heading" style="color:black">
                    {{category.category_Name}}
                </h1>
                </div>
                <div class="description" style="color:#5A5B5E">
                    {{category.category_Description}}

                </div>

            </div>

            <div class="right-side">
                <img src="/{{category.category_Image}}">

            </div>
        </div>
        <div class="view_main">
            <div class="view_wrap list-view" style="display: block;">

                {% for i in category.courses_set.all %}
                <div class="view_item">
                    <div class="vi_left">
                        <img src="/{{i.course_Image}}" alt="Relevant Image">
                    </div>
                    <div class="vi_right">
                        <p class="title">{{i.course_Name}}</p>
                        <p class="content" style="overflow:hidden;
                        display:-webkit-box;
                        -webkit-box-orient:vertical;
                        -webkit-line-clamp:2">
                            {{i.course_Description}}</p>
                        <div class="btn">Explore ></div>
                    </div>
                </div>
                 {% endfor %}

            </div>
        </div>
    </div>

</div>
    <script>
        var li_links = document.querySelectorAll(".links ul li");
        var view_wraps = document.querySelectorAll(".view_wrap");
        var list_view = document.querySelector(".list-view");
        var grid_view = document.querySelector(".grid-view");

        li_links.forEach(function(link){
            link.addEventListener("click", function(){
                li_links.forEach(function(link){
                    link.classList.remove("active");
                })

                link.classList.add("active");

                var li_view = link.getAttribute("data-view");

                view_wraps.forEach(function(view){
                    view.style.display = "none";
                })

                if(li_view == "list-view"){
                    list_view.style.display = "block";
                }
                else{
                    grid_view.style.display = "block";
                }
            })
        })

    </script>

<!--<script type="text/javascript">-->
<!--    document.getElementById("myButton").onclick = function () {-->
<!--        location.href = "/materials/courses/";-->
<!--    };-->
<!--</script>-->
    {% endblock main_content %}